name: Generate Test Report and Deploy

on:
  push:
    branches: [ main ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Install ReportGenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool

    - name: Run Tests and Generate .trx
      run: dotnet test --logger "trx;LogFileName=test_results.trx"

    - name: Generate HTML Report
      run: reportgenerator -reports:"**/test_results.trx" -targetdir:"test-reports" -reporttypes:Html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./test-reports
        publish_branch: gh-pages
