name: Run .NET Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' # oder deine Version

    - name: Restore dependencies
      run: dotnet restore Prototype_Tests/Prototype_Tests.sln


    - name: Build solution
      run: dotnet build Prototype_Tests/Prototype_Tests.sln --no-restore

    - name: Run tests
      run: dotnet test Prototype_Tests/Prototype_Tests.sln --no-build --verbosity normal

